### ISSUE TITLE
Car

### ISSUE THREAD

**Issue by kka-na** [inha-cvl/CoLaneX#2]
Chem OBU로 상대 차량 ID, 속도, 위치 받아서 ROS Topic Message 로 만들기

- [x]  IONIQ, i30 두 차량 각각에 대해서  위에 세개 값 받기
    - OBU통신하는 코드에서, ROS로 받기 (C, C++)
    - KIAPI2022코드 참고
    - **나중에 소켓 통신 하는 부분만 켐트로닉스 OBU** 로 바꿀 수 있게
- [x]  OBU연결하고 차량에서 상태 값 받고 BSM Encoding
    - KIAPI2022 코드 참고
    - 위도, 경도, 속도, 헤딩, ID 를 주요하게 넣기
- [x]  Rx Receive해서 상대 차량 데이터 받기
    - 받은 데이터는 ROS Topic화
        - 내 차량이 Publish하는 토픽과 이름은 같지만 /private/ 이름으로 만들기

**Comment by q-code-git** [comment]
https://guruhong.tistory.com/entry/%EC%9A%B0%EB%B6%84%ED%88%AC-%ED%95%98%EB%93%9C-%EB%B3%B5%EC%82%AC

https://www.youtube.com/watch?v=I998Fr7VGJA

**Comment by q-code-git** [comment]
- mrd 1000 v2를 노트북에 연결하여 다시 테스트 해보기(파워케이블 뒷자리)
- mrp 2000 gnss 수신 안 되는 원인 찾기(mrd 1000 v2는 수신이 됨)
- mrd 1000 v2, mrp 2000 설정 창에서 데이터 출력 설정 확인하기
- LTE 안테나 연결 상태 확인하기

**Comment by q-code-git** [comment]
- mrd 1000 v2
gnss 값 수신 확인(단말 디스플레이 출력 O)
LTE 망 연결 됨
시리얼로 값이 출력은 되나 checksum 문제 발생 

- mrp 2000
gnss 값 수신 안됨(단말 디스플레이 출력 X)
LTE 망 연결 됨

LTE 보증 기간 끝났는지 서비스센터에 문의할 것

**Comment by kka-na** [comment]
**Pose from OBU**
car/obu.py
OBU장치에서 Pose 데이터 (위도, 경도, 헤딩, 속도) Publish.
SSH를 통해 원격 장치에 접속하고, 그 장치에서 GPS 데이터를 읽어와 ROS 노드로 게시하는 역할. 

Execute: $python3 obu.py hlv/tlv

OBU장치 내의 CGPS가 동작되고 있는 Ettiffos장치에 ssh로 접근해서 출력되는 GPS정보와 자세 정보 가져옴 
1. 주어진 호스트명, 포트, 사용자명, 비밀번호 사용해서 ssh연결.
2. paramiko 라이브러리 사용해서 ssh 세션 만들고, 셸 호출해서 chan에 세션 저장. (명령을 보내고 결과르 받는 작업에 사용되는 객체)
3. paramiko 라이브러리의 send함수 이용해서 원격 셸에 명령 전송 'gpspipe -w -n 0' : GPS 데이터를 실시간으로 확인하ㅡㄴ 함수
4. chan.recv_ready() : ssh세션에서 데이터 받을 준비 되었는지 확인.
5. data = chan.recv(9600).decode('utf-8') : ssh세션에서 최대 9600 바이트 데이터 읽음. 그 다음 utf-8인코딩 사용해서 데이터를 문자열로 디코딩해서 data에 저장. 
6. matches = re.findall(~) : 정규 표현식을 사용해서  문자열에서 lat, lon, speed, track과 해당하는 실수 값을 찾아서 리스트로 반환함.

**Comment by inha-cvl** [comment]
The project has concluded.
