### ISSUE TITLE
 Planning

### ISSUE THREAD

**Issue by kka-na** [inha-cvl/CoLaneX#5]
- [x] 컴퓨터 RViz시뮬레이터로 확인할 수 있는 가상 vehicle 데이터 publisher
- [x] RViz layout
- [x] 동적 경로 생성 알고리즘
- [x] 안전 거리 계산 알고리즘

**Comment by kka-na** [comment]
**Safe Distance**
- HDMap 기반 직진 경로 무한 생성 가능
- 경로는 속도 비례한 일정 거리에 도달 시 직진 경로로 갱신 됨
- 경로 갱신이 필요한 경우 ( 경로를 새로 생성할 때, 경로 끝 까지 현재속도(km/h) m 만큼 남았을 때 ) 
- 기존 경로는 유지 + 경로 끝 부분에 이어서 갱신 됨
- GeoJson변환 함수 -> planner_utils로
- straight path를 만드는 함수 -> planner_utils로 
- visualize를 위해서 compressing하는 함수 생성 및 planner utils에 있음. 
- 기존 변곡점 부분만 넘기니깐 visualize 시 이상해 보임 -> 몇개 단위로 자를지 인자를  input으로 넘겨서 그만큼 압축할 수 있음.

**Comment by kka-na** [comment]
**Planner Utils**

Get Whole Neighbor
: 현재 lane 에서 모든 이웃, 즉 전체 차선에 해당하는 차선 정보를 얻을 수 있는 함수
- left most, right most까지 가서 left lane은 왼쪽부터 0,1,2, 오른쪽은 오른쪽부터 0,1,2로 리스트로 반환
- 내가 현재 어느 차선에 있는지에 대한 인덱스도 반환

Find Most Successor
: 내가 있는 전체 차선에 서 왼쪽, 오른쪽 차선들의 정보를 입력으로 받아서 successor가 있는 차선을 찾아냄
- 나한테 연결된 successor가 없을 때 이웃의 successor로 연결하기 위함
문제) 원래는 갈 수 없는 길인데 무조건 연결하기 때문에 갈 수 있어버림 (역주행을 하지는 않음)

Get Possible Successor
: 내가 있는 차선에서 다음 경로에 있는 successor를 오류 없이, 계속 이어지는 코스를 구하기 위함
- prior은 만약 내 다음 경로 가없을 때, 어느 방향부터 탐색을 시작할지에 대한 인자로, 기본 값은 왼쪽임
- 즉 내 다음 연결된 차선이 없을 때, 왼쪽에 있는 차선의 successor 부터 확인하겠다는 의미 만약 왼쪽에도 없으면 오른쪽으로 넘어간다. 
- 왼쪽, 오른쪽에 있는 차선들은 get possible successor로 얻어온다. 
- 그 다음에 find most successor를 이용해서 왼쪽, 오른쪽 차선에서 찾을 수 있는 가장 가까운 sucessor를 얻는다. 

Get Straight Path
: 여러 레인을 걸쳐가며 주어진 시작 인덱스와 경로 길이에 따라 직선 경로를 추출하도록 설계
: lanelet에서 successor가 없으면 경로 갱신을 멈춰 버리는 경우를 없애기 위해 자연스러운 successor를 찾는 부분을 추가
: HLV, TLV 각각에서 동일한 함수를 사용하기 때문에 planner utils로 옮김

- 현재 노드(s_n)와 현재 차선에서 해당하는 인덱스(s_i)를 인자로, 생성할 경로의 길이(path_len)를 인자로 받는다

1. 주어진 시작 레인 정보 lanelet[s_n]에서 waypoints를 가져옵니다.
2. path_len을 인덱스 단위로 변환하여 s_i에 더합니다. 
3. u_n과 u_i를 각각 s_n과 계산된 s_i로 설정합니다.
4. 만약 u_i가 현재 레인의 waypoints 개수보다 크거나 같다면, 다른 레인으로 이동해야 합니다. 이때, 왼쪽 방향으로 가능한 다음 레인을 찾아 _u_n에 저장합니다.
5. 만약 _u_n이 None이라면, 더 이상 왼쪽으로 이동할 수 있는 레인이 없으므로 현재 레인의 마지막 waypoints까지 이동하게 됩니다.
그렇지 않은 경우, 다음 레인으로 이동하고 u_i를 현재 레인의 길이 만큼 감소시키며, e_i를 이동한 거리만큼 증가시킵니다.
6. 이동한 레인의 waypoints를 u_wp로 가져오고, lls_len을 업데이트합니다.
7. 현재 레인의 waypoints에 이동한 레인의 waypoints를 추가합니다.
8. 최종적으로 추출한 경로를 s_i부터 e_i까지의 인덱스 범위로 설정하여 r에 저장합니다.
9. 추출한 경로 r, 마지막으로 이동한 레인의 인덱스 u_n, 그리고 마지막으로 남은 u_i 값을 반환합니다.

Do Compressing
: 어떤 리스트가 들어왔을 때, 처음과 끝 점은 유지하고 그 안에 다른 데이터의 간격을 일정하게 distillation하는 함수

**Comment by kka-na** [comment]
https://github.com/inha-cvl/CoLaneX/blob/0b7e2d20a4c655d4f0b399d591d138f825f09a23/planning/tlv_planning.py#L195-L203

tlv_planning.py에서 처음 결정한 safety를 믿고, 4틱이 쌓이면 safety confirm,더이상 검사하지 않고, 
중간에 다른 safety계산이 들어오면 멈추게끔 하였음 -> 이부분 예외처리 필요

confirm하는거 초기화 하는거는 tlv에서 < > 누르거나 중간에 - 누르면 바로 초기화 됨. 
--> 초기화 안하면, 다음 safety구할 때 동작하지 않음

**Comment by inha-cvl** [comment]
The project has concluded.
